### ISSUE TITLE
make static output for submitting the paper for peer review

### ISSUE THREAD

**Issue by LinguList** [clld/clts#2]
If static HTML output is not too complicated, I'd suggest to prepare a static output and submit the zip folder to the peer review, as this will make it possible to have it anonymous.

**Comment by xrotwang** [comment]
You mean static HTML for the whole site?

**Comment by LinguList** [comment]
Yes, or is that too much? I have no real idea of how complicated this is, and how much space it will cover in terms of MB.

**Comment by xrotwang** [comment]
The individual resource pages are not much of a problem, but the datatables require a server backend. I guess one could create static resource index pages - replacing the datatables with static HTML tables. But then much of the functionality would disappear. So, presumably a screenshot / dump of a single details page would be enough?

**Comment by LinguList** [comment]
Yes, we can also for the time being proceed like this:

1. we prepare the app, but we do not need to finalize everything by end of this month
2. we submit a screenshot and the js-code for the little app which I made before to illustrate the general functionality
3. we submit the clts-package
4. we say in the remainder that the clld-app will be published if the paper is accepted, as we cannot publish it anonymously for now

This will take some pressure from us, and we can quietly start with some version 0.1, which we may even share upon request (I anyway do not really believe that this will be completely anonymous peer-review, as it is easy to see who is doing this ;). But we would not have to publish a fully committed version 1.0 before this paper went through review (and hopefully gets accepted).

**Comment by xrotwang** [comment]
Ah, yes. I think a web app is too volatile to be a substantial and fixed part of a publication.

**Comment by LinguList** [comment]
So I'll close this now, and once we meet end of this week, I suggest, we quickly discuss a plan of when to publish what.
