### ISSUE TITLE
Follow Moran&Cysouw's strict-IPA?

### ISSUE THREAD

**Issue by Anaphory** [clld/clts#5]
Do we want to follow the strict-IPA in the Unicode Cookbook?

I think we could distill a lot of the pitfalls and examples they list into test cases for `pyclts`, but I'm not sure what this would mean for CLTS online.

**Comment by LinguList** [comment]
We have been there already, and since in practice nobody is following strict IPA, we can forget about this. We could provide a strict IPA as a transcription system, where you restrict cases that we do allow in bipa (sipa), this was the original plan, but somebody would have to go through the cases and write this up.

**Comment by Anaphory** [comment]
I was more thinking about our output. For example, currently we don't normalize g→ɡ, but we could.

> Second, we commonly encounter the use of <g> latin small letter g at U+0067, instead of the Unicode Standard IPA character for the voiced velar stop <ɡ> latin small letter script g at U+0261. […] For strict IPA encoding we propose to standardize on the more idiosyncratic latin small letter script g at U+0261.

```
>>> import pyclts
>>> bipa = pyclts.TranscriptionSystem()
>>> bipa("g")
[<pyclts.models.Consonant: voiced velar stop consonant>]
>>> hex(ord(str(bipa("g")[0])))
'0x67'
```

**Comment by xrotwang** [comment]
I think @Anaphory has a point here. In particular considering that we **do** normalize:
```python
>>> hex(ord(str(bipa("\u0261")[0])))
'0x67'
```

So since we do normalize, I think it would be easiest (in terms of documentation at least) to normalize according to strict-IPA.

**Comment by Anaphory** [comment]
I assume there are several other such cases (tone letters? diacritic ordering?) where we could change our output to conform to strict-IPA as much as possible, like we already do in other cases:

```
>>> hex(ord(str(bipa("!")[0])))
'0x1c3'
>>> str(bipa("a:")[0])
'aː'
>>> hex(ord(str(bipa("th")[0])[1]))
'0x2b0'
```

**Comment by LinguList** [comment]
I deliberately don't normalize the g-case, as I feel that this is going counter the normal perception of people in using a specific letter for such a normal sound. And to my knowledge, this is the only case that occurs there. Or do you see other cases other than g? Our diacritics are correct, as far as I can see, as we fix the order (in contrast to the phoible database), etc. Furthermore, the cookbook does not mention all of the variables. 

So, we already try to normalize, but I do not find the info in the book sufficient, and there are specific cases, where you can't follow their prescriptions, specifically, if it is dubious (see the case of "pharyngealization vs. velarization" on p. 55.

I'd say, if one of the contributors finds time to list the cases, please propose a list here, and we discuss them token by token. I will strictly oppose against the stupid special g-character, as this is de facto not used by nobody.

**Comment by LinguList** [comment]
follow up on tones: we also decided that we would not follow IPA here, as their tones are barely used and superscript letters are the quasi-standard.

**Comment by LinguList** [comment]
Reading the passage in the book again, IPA allows both g-glyphs, and the whole section in the book is rather written in prose form, no code or no list of symbols or whatsoever is provided. For this reason, I'd say, that our BIPA is proposing a solution to make this strict. We can discuss all characters, but the book by Moran and Cysouw is not what I would accept as standard, as it is just an interpretation taht could well be discussed in detail.

**Comment by Anaphory** [comment]
“No” is a valid answer to my question of “should we follow?”, but part of the point of their book is specifically to move from “one interpretation among many technologically-incompatible ones” to “the one specific, reasonable interpretation, which can serve as the normalization standard”, so your last reply is not a very strong argument for “No”. (Other points you raise are obviously valid.)

I also find their choice of `U+0261` instead of `U+0067` for [g] strangely contrarian, in particular because IPA specifically removed the requirement to use `U+0261` *because* no-one was using it, but in principle I prefer everyone picking one and sticking with it to both being options that need explicit consideration. The fact that CLTS accepts both and normalizes to something is very helpful already (same for all other shiny resolved ambiguities), so I'm perfectly fine with everyone adopting CLTS-BIPA instead of Cookbook-sIPA.

Actually, the lists of code points are there, collected in one specific location just at the end of the chapter we are discussing right now. Specifically, Table 5.4 on p. 78 vs. the part of Table 5.1 on p. 73 for my `g` example. There are 3 objects in Table 5.4 that are not tone diacritics (I have no opinion that something should be done with tone diacritics, because I don't know how), which would make valid test cases: `g`, ring above instead of below, and tie bar below.

For tie bars, their recommendation, as well as our praxis in BIPA, is to avoid them generally by explicitly tokenizing.

Rings above we are already normalizing.
```
>>> str(bipa("å")[0])
'ḁ'
```

Therefore I assume that tones and g/ɡ are the only cases where BIPA and strict-IPA differ. I think it would be worth making that explicit through tests, and to provide the tiny `to_strict_ipa` function which just does `g ¹ ² ³ ⁴ ⁵`→`ɡ ˩ ˨ ˧ ˦ ˥`.

**Comment by xrotwang** [comment]
For me, the situation here is a lot like with programming style guides:
it's important to follow one, but less important which one. So the real
benefit of following the book - even if this still requires some
interpretation - is that we don't have to write an alternative book
ourselves.

Gereon Kaiping <notifications@github.com> schrieb am Fr., 21. Sep. 2018,
17:08:

**Comment by LinguList** [comment]
We can add another TS calling it MoranCysouw, and this is it, I'd say, or call it strict IPA, and we can again discuss item by item of the sparse list in the book. But I'll insist on keeping those cases that I explicitly did not follow, line tones and the g in BIPA. There's a reason I didn't call it SIPA. I mean: that's what CLTS is about: offer different transciption systems. And BIPA serves practical purposes, which we can even explain more detailed in the paper. SIPA was not proposed for existing data, but for ideal data, I always wanted to add this, but not by overwriting BIPA.

**Comment by LinguList** [comment]
BTW: this is the wrong place for the issue, it should be [here](https://github.com/cldf/clts/issues).

**Comment by LinguList** [comment]
And here's our former discussion on strict ipa: https://github.com/cldf/clts/issues/60

**Comment by LinguList** [comment]
so, my final point on this, for a UnicodeCookbookStrictIpa, you basically only need to change the [normalise](https://github.com/cldf/clts/blob/master/src/pyclts/transcriptionsystems/bipa/normalize.tsv) file, which explicitly turns the strange "g" to a normal "g" as well as the tone marks. But this would be another TS, call it "sipa" or whatever.

**Comment by LinguList** [comment]
I just moved the issue, this here should be closed.

**Comment by Anaphory** [comment]
> BTW: this is the wrong place for the issue, it should be here.

Right!
